package com.example.test_android_green_dao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.test_android_green_dao.dao.Techer;
import com.example.test_android_green_dao.dao.Student;

import com.example.test_android_green_dao.dao.TecherDao;
import com.example.test_android_green_dao.dao.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig techerDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final TecherDao techerDao;
    private final StudentDao studentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        techerDaoConfig = daoConfigMap.get(TecherDao.class).clone();
        techerDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        techerDao = new TecherDao(techerDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(Techer.class, techerDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        techerDaoConfig.getIdentityScope().clear();
        studentDaoConfig.getIdentityScope().clear();
    }

    public TecherDao getTecherDao() {
        return techerDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
